-- Migration: Change user id from BIGSERIAL to UUID
-- Description: Converts the id column from BIGSERIAL to UUID type

-- Step 1: Drop primary key constraint
ALTER TABLE IF EXISTS users DROP CONSTRAINT IF EXISTS users_pkey;

-- Step 2: Add a new temporary UUID column
ALTER TABLE users ADD COLUMN IF NOT EXISTS id_new UUID;

-- Step 3: Generate UUIDs for existing records (if any)
UPDATE users SET id_new = gen_random_uuid() WHERE id_new IS NULL;

-- Step 4: Make the new column NOT NULL
ALTER TABLE users ALTER COLUMN id_new SET NOT NULL;

-- Step 5: Drop the old id column (this removes the identity property)
ALTER TABLE users DROP COLUMN IF EXISTS id;

-- Step 6: Rename the new column to id
ALTER TABLE users RENAME COLUMN id_new TO id;

-- Step 7: Set id as primary key
ALTER TABLE users ADD PRIMARY KEY (id);

-- Step 8: Add default value for new records (UUID will be generated by Hibernate)
ALTER TABLE users ALTER COLUMN id SET DEFAULT gen_random_uuid();

-- Step 9: Update comments
COMMENT ON COLUMN users.id IS 'Unique identifier for the user (UUID)';
